# Generated by Django 2.0 on 2019-01-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='Subrediti',
            new_name='subrediti',
        ),
    ]
