# Generated by Django 2.0 on 2019-01-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0003_auto_20190118_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likethread',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
