# Generated by Django 2.0 on 2019-01-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0004_auto_20190118_1310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='likethread',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='likethread',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='likethread',
            name='user',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
        migrations.DeleteModel(
            name='LikeThread',
        ),
    ]
